import {useEffect,useState} from 'react';
import {ChatWindow} from './components/ChatWindow';
import {ChatErrorBoundary} from './components/ChatErrorBoundary';
const API=import.meta.env.VITE_API_URL||'http://127.0.0.1:8000';
type FieldErrors=Record<string,string>;
function messageFromDetail(detail:any):string{return Array.isArray(detail)?detail.map(x=>x.msg).join(', '):String(detail||'Could not sign in.');}

export default function PortalApp(){
 const [token,setToken]=useState(()=>localStorage.getItem('pcos_token')||'');
 const [checking,setChecking]=useState(Boolean(localStorage.getItem('pcos_token')));
 const [notice,setNotice]=useState('');
 const [mode,setMode]=useState<'login'|'register'>('login');
 const [fullName,setFullName]=useState('');const [email,setEmail]=useState('');const [phone,setPhone]=useState('');const [password,setPassword]=useState('');const [confirmPassword,setConfirmPassword]=useState('');
 const [error,setError]=useState('');const [fieldErrors,setFieldErrors]=useState<FieldErrors>({});const [busy,setBusy]=useState(false);
 const clearToken=()=>{localStorage.removeItem('pcos_token');setToken('');setChecking(false)};
 const unauthorized=()=>{clearToken();setNotice('Your session expired, please log in again.')};
 useEffect(()=>{if(!token)return;fetch(`${API}/auth/me`,{headers:{Authorization:`Bearer ${token}`}}).then(r=>{if(!r.ok)unauthorized()}).catch(()=>{clearToken();setNotice('Your session could not be verified. Please log in again.')} ).finally(()=>setChecking(false))},[]);
 const validate=():boolean=>{const next:FieldErrors={};if(mode==='register'&&!fullName.trim())next.full_name='Please enter your full name.';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim()))next.email='Enter a valid email address.';if(mode==='register'){const digits=phone.replace(/[\s+-]/g,'');if(!/^\+?[0-9\s-]+$/.test(phone)||digits.length<10||digits.length>15)next.phone='Enter a phone number with 10–15 digits.';if(password.length<8)next.password='Use at least 8 characters.';if(password!==confirmPassword)next.confirm_password='Passwords do not match.';}else if(password.length<8)next.password='Use at least 8 characters.';setFieldErrors(next);return Object.keys(next).length===0};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(!validate())return;setBusy(true);try{const body=mode==='register'?{full_name:fullName,email,phone,password}:{email,password};const r=await fetch(`${API}/auth/${mode==='register'?'register':'login'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(messageFromDetail(data.detail));localStorage.setItem('pcos_token',data.access_token);setToken(data.access_token);setPassword('');setConfirmPassword('');setNotice('')}catch(err){setError(err instanceof Error?err.message:'Request failed.')}finally{setBusy(false)}};
 const inputClass='mt-1 w-full rounded-xl border border-accent-soft bg-white px-3 py-3 text-ink outline-none focus:ring-2 focus:ring-accent';
 if(checking)return <main className="grid min-h-dvh place-items-center bg-bg px-4 text-sm text-ink">Checking your sign-in…</main>;
 if(token)return <ChatErrorBoundary key={token}><ChatWindow token={token} onLogout={clearToken} onUnauthorized={unauthorized}/></ChatErrorBoundary>;
 return <main className="grid min-h-dvh place-items-center bg-bg px-4 py-5 text-ink sm:py-8"><form onSubmit={submit} noValidate className="w-full max-w-md rounded-3xl border border-accent-soft bg-white p-5 shadow-sm sm:p-8"><div className="mb-5 text-center"><img src="/narisaarthi-logo.png" alt="Narisaarthi logo" className="mx-auto h-20 w-20 rounded-full object-cover sm:h-24 sm:w-24"/><h1 className="mt-3 text-xl font-semibold">PCOS Detection &amp; Pre-Diagnosis</h1><p className="mt-1 text-sm font-medium">Narisaarthi · Empower Your PCOS Journey</p><p className="mt-3 text-sm">{mode==='login'?'Welcome back':'Create your account'}</p><p className="mt-1 text-sm">Your account keeps your screening history together.</p></div>
 {mode==='register'&&<label className="mb-3 block text-sm">Full name<input autoComplete="name" value={fullName} onChange={e=>setFullName(e.target.value)} className={inputClass}/>{fieldErrors.full_name&&<small className="text-ink">{fieldErrors.full_name}</small>}</label>}
 <label className="mb-3 block text-sm">Email<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} className={inputClass}/>{fieldErrors.email&&<small className="text-ink">{fieldErrors.email}</small>}</label>
 {mode==='register'&&<label className="mb-3 block text-sm">Phone<input type="tel" autoComplete="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+1 555 123 4567" className={inputClass}/>{fieldErrors.phone&&<small className="text-ink">{fieldErrors.phone}</small>}</label>}
 <label className="mb-3 block text-sm">Password<input type="password" autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)} className={inputClass}/>{fieldErrors.password&&<small className="text-ink">{fieldErrors.password}</small>}</label>
 {mode==='register'&&<><label className="mb-3 block text-sm">Confirm password<input type="password" autoComplete="new-password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} className={inputClass}/>{fieldErrors.confirm_password&&<small className="text-ink">{fieldErrors.confirm_password}</small>}</label><p className="mb-4 text-xs text-ink">Your details are used only for your account and screening history.</p></>}
 {(notice||error)&&<p role="alert" className="mb-3 rounded-lg bg-accent-soft px-3 py-2 text-sm text-ink">{notice||error}</p>}<button disabled={busy} className="w-full rounded-xl bg-accent py-3 font-medium text-ink hover:bg-accent-soft disabled:opacity-50">{busy?'Please wait…':mode==='login'?'Sign in':'Register'}</button><button type="button" onClick={()=>{setMode(mode==='login'?'register':'login');setError('');setFieldErrors({})}} className="mt-4 w-full rounded-lg py-2 text-sm font-medium text-ink underline decoration-accent hover:bg-accent-soft">{mode==='login'?"New here? Create an account":"Already registered? Sign in"}</button><p className="mt-6 rounded-xl bg-accent-soft p-3 text-xs leading-5 text-ink">A screening estimate, not a diagnosis. Please consult a doctor about personal health concerns.</p></form></main>
}
